### ISSUE TITLE
interdigitTimeout is now available and needs included

### ISSUE THREAD

**Issue by JustinDupree** [tropo/tropo-webapi-python#25]
https://www.tropo.com/docs/webapi/ask.htm

https://www.tropo.com/docs/webapi/conference.htm

https://www.tropo.com/docs/webapi/record.htm

https://www.tropo.com/docs/webapi/transfer.htm

**Comment by frankmeten** [comment]
I checked it, and that had been included.
So can we close this issue?
@JustinDupree
